### PR TITLE
:sparkles: Add Curry function for 1 arity (#24)

### LINKED ISSUE #24: Any reason why the Currying starts with Function2 instead of Function1?
Actually this is not an issue, but unfortunately I found no other place to ask. 

Attempting to write a deserializer for a data-class holding only one field e.g. `data class Pet(val name: String)` I was struggling to find a matching Currying i.e. create function since it seems that the Currying starts with Function2.

code: https://github.com/kittinunf/Forge/blob/223e0a9fb05b20eb16bac38d5d246882f9eb271e/forge/src/main/kotlin/com/github/kittinunf/forge/util/Currying.kt#L3

### PR DESCRIPTION
**Pull request by janjaali**
Provides currying function for single data field classes enabling clients to use the familiar syntax to create `Deserializable`'s also from these single data fields:

```kotlin
data class Pet(val name: String)

val deserializer: (JSON) -> DeserializedResult<Pet> = { json: JSON ->
  ::Pet.create.map(json at "name")
}
```

Relates to #24.

closes #24

### CODE REVIEW

**Comment by kittinunf** [comment]
Hmm, the CI seems to be broken. Please let me fix in the different PR 🙏

**Comment by kittinunf** [comment]
Could you please rebase against the updated master for the CI fix?

**Comment by janjaali** [comment]
Sure, the build is back green now, thx .)

**Comment by kittinunf** [comment]
Awesome, merging this in 😄

**Pull request merged**
